class Status {
	static CONTINUE: any = 100;
	static SWITCHING_PROTOCOLS: any = 101;
	static PROCESSING: any = 102; // RFC2518
	static EARLY_HINTS: any = 103; // RFC8297
	static OK: any = 200;
	static CREATED: any = 201;
	static ACCEPTED: any = 202;
	static NON_AUTHORITATIVE_INFORMATION: any = 203;
	static NO_CONTENT: any = 204;
	static RESET_CONTENT: any = 205;
	static PARTIAL_CONTENT: any = 206;
	static MULTI_STATUS: any = 207; // RFC4918
	static ALREADY_REPORTED: any = 208; // RFC5842
	static IM_USED: any = 226; // RFC3229
	static MULTIPLE_CHOICES: any = 300;
	static MOVED_PERMANENTLY: any = 301;
	static FOUND: any = 302;
	static SEE_OTHER: any = 303;
	static NOT_MODIFIED: any = 304;
	static USE_PROXY: any = 305;
	static RESERVED: any = 306;
	static TEMPORARY_REDIRECT: any = 307;
	static PERMANENTLY_REDIRECT: any = 308; // RFC7238
	static BAD_REQUEST: any = 400;
	static UNAUTHORIZED: any = 401;
	static PAYMENT_REQUIRED: any = 402;
	static FORBIDDEN: any = 403;
	static NOT_FOUND: any = 404;
	static METHOD_NOT_ALLOWED: any = 405;
	static NOT_ACCEPTABLE: any = 406;
	static PROXY_AUTHENTICATION_REQUIRED: any = 407;
	static REQUEST_TIMEOUT: any = 408;
	static CONFLICT: any = 409;
	static GONE: any = 410;
	static LENGTH_REQUIRED: any = 411;
	static PRECONDITION_FAILED: any = 412;
	static REQUEST_ENTITY_TOO_LARGE: any = 413;
	static REQUEST_URI_TOO_LONG: any = 414;
	static UNSUPPORTED_MEDIA_TYPE: any = 415;
	static REQUESTED_RANGE_NOT_SATISFIABLE: any = 416;
	static EXPECTATION_FAILED: any = 417;
	static I_AM_A_TEAPOT: any = 418; // RFC2324
	static MISDIRECTED_REQUEST: any = 421; // RFC7540
	static UNPROCESSABLE_ENTITY: any = 422; // RFC4918
	static LOCKED: any = 423; // RFC4918
	static FAILED_DEPENDENCY: any = 424; // RFC4918
	static TOO_EARLY: any = 425; // RFC-ietf-httpbis-replay-04
	static UPGRADE_REQUIRED: any = 426; // RFC2817
	static PRECONDITION_REQUIRED: any = 428; // RFC6585
	static TOO_MANY_REQUESTS: any = 429; // RFC6585
	static REQUEST_HEADER_FIELDS_TOO_LARGE: any = 431; // RFC6585
	static UNAVAILABLE_FOR_LEGAL_REASONS: any = 451; // RFC7725
	static INTERNAL_SERVER_ERROR: any = 500;
	static NOT_IMPLEMENTED: any = 501;
	static BAD_GATEWAY: any = 502;
	static SERVICE_UNAVAILABLE: any = 503;
	static GATEWAY_TIMEOUT: any = 504;
	static VERSION_NOT_SUPPORTED: any = 505;
	static VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL: any = 506; // RFC2295
	static INSUFFICIENT_STORAGE: any = 507; // RFC4918
	static LOOP_DETECTED: any = 508; // RFC5842
	static NOT_EXTENDED: any = 510; // RFC2774
	static NETWORK_AUTHENTICATION_REQUIRED: any = 511; // RFC6585

	static CONTINUE_MESSAGE: string = "Continue";
	static SWITCHING_PROTOCOLS_MESSAGE: string = "Switching Protocols";
	static PROCESSING_MESSAGE: string = "Processing"; // RFC2518
	static EARLY_HINTS_MESSAGE: string = "Early Hints";
	static OK_MESSAGE: string = "OK";
	static CREATED_MESSAGE: string = "Created";
	static ACCEPTED_MESSAGE: string = "Accepted";
	static NON_AUTHORITATIVE_INFORMATION_MESSAGE: string = "Non-Authoritative Information";
	static NO_CONTENT_MESSAGE: string = "No Content";
	static RESET_CONTENT_MESSAGE: string = "Reset Content";
	static PARTIAL_CONTENT_MESSAGE: string = "Partial Content";
	static MULTI_STATUS_MESSAGE: string = "Multi-Status"; // RFC4918
	static ALREADY_REPORTED_MESSAGE: string = "Already Reported"; // RFC5842
	static IM_USED_MESSAGE: string = "IM Used"; // RFC3229
	static MULTIPLE_CHOICES_MESSAGE: string = "Multiple Choices";
	static MOVED_PERMANENTLY_MESSAGE: string = "Moved Permanently";
	static FOUND_MESSAGE: string = "Found";
	static SEE_OTHER_MESSAGE: string = "See Other";
	static NOT_MODIFIED_MESSAGE: string = "Not Modified";
	static USE_PROXY_MESSAGE: string = "Use Proxy";
	static RESERVED_MESSAGE: string = "Reserved";

	static TEMPORARY_REDIRECT_MESSAGE: string = "Temporary Redirect";
	static PERMANENTLY_REDIRECT_MESSAGE: string = "Permanent Redirect"; // RFC7238
	static BAD_REQUEST_MESSAGE: string = "Bad Request";
	static UNAUTHORIZED_MESSAGE: string = "Unauthorized";
	static PAYMENT_REQUIRED_MESSAGE: string = "Payment Required";
	static FORBIDDEN_MESSAGE: string = "Forbidden";
	static NOT_FOUND_MESSAGE: string = "Not Found";
	static METHOD_NOT_ALLOWED_MESSAGE: string = "Method Not Allowed";
	static NOT_ACCEPTABLE_MESSAGE: string = "Not Acceptable";
	static PROXY_AUTHENTICATION_REQUIRED_MESSAGE: string = "Proxy Authentication Required";
	static REQUEST_TIMEOUT_MESSAGE: string = "Request Timeout";
	static CONFLICT_MESSAGE: string = "Conflict";
	static GONE_MESSAGE: string = "Gone";
	static LENGTH_REQUIRED_MESSAGE: string = "Length Required";
	static PRECONDITION_FAILED_MESSAGE: string = "Precondition Failed";
	static REQUEST_ENTITY_TOO_LARGE_MESSAGE: string = "Content Too Large"; // RFC-ietf-httpbis-semantics
	static REQUEST_URI_TOO_LONG_MESSAGE: string = "URI Too Long";
	static UNSUPPORTED_MEDIA_TYPE_MESSAGE: string = "Unsupported Media Type";
	static REQUESTED_RANGE_NOT_SATISFIABLE_MESSAGE: string = "Range Not Satisfiable";
	static EXPECTATION_FAILED_MESSAGE: string = "Expectation Failed";
	static I_AM_A_TEAPOT_MESSAGE: string = "I'm a teapot"; // RFC2324
	static MISDIRECTED_REQUEST_MESSAGE: string = "Misdirected Request"; // RFC7540
	static UNPROCESSABLE_ENTITY_MESSAGE: string = "Unprocessable Content"; // RFC-ietf-httpbis-semantics
	static LOCKED_MESSAGE: string = "Locked"; // RFC4918
	static FAILED_DEPENDENCY_MESSAGE: string = "Failed Dependency"; // RFC4918
	static TOO_EARLY_MESSAGE: string = "Too Early"; // RFC-ietf-httpbis-replay-04
	static UPGRADE_REQUIRED_MESSAGE: string = "Upgrade Required"; // RFC2817
	static PRECONDITION_REQUIRED_MESSAGE: string = "Precondition Required"; // RFC6585
	static TOO_MANY_REQUESTS_MESSAGE: string = "Too Many Requests"; // RFC6585
	static REQUEST_HEADER_FIELDS_TOO_LARGE_MESSAGE: string = "Request Header Fields Too Large"; // RFC6585
	static UNAVAILABLE_FOR_LEGAL_REASONS_MESSAGE: string = "Unavailable For Legal Reasons"; // RFC7725
	static INTERNAL_SERVER_ERROR_MESSAGE: string = "Internal Server Error";
	static NOT_IMPLEMENTED_MESSAGE: string = "Not Implemented";
	static BAD_GATEWAY_MESSAGE: string = "Bad Gateway";
	static SERVICE_UNAVAILABLE_MESSAGE: string = "Service Unavailable";
	static GATEWAY_TIMEOUT_MESSAGE: string = "Gateway Timeout";
	static VERSION_NOT_SUPPORTED_MESSAGE: string = "HTTP Version Not Supported";
	static VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL_MESSAGE: string = "Variant Also Negotiates"; // RFC2295
	static INSUFFICIENT_STORAGE_MESSAGE: string = "Insufficient Storage"; // RFC4918
	static LOOP_DETECTED_MESSAGE: string = "Loop Detected"; // RFC5842
	static NOT_EXTENDED_MESSAGE: string = "Not Extended"; // RFC2774
	static NETWORK_AUTHENTICATION_REQUIRED_MESSAGE: string = "Network Authentication Required"; // RFC6585
	static NETWORK_UNASSIGNED_MESSAGE: string = "Unassigned"; // RFC6585
}

export { Status };
export default Status;
